### PR TITLE
notebook script for plotting

### PR DESCRIPTION
**Pull request by fmyuan**
Shawn,

I add a ipynb script to plot ELM output for any variable. When open it in notebook, user can customize what variable to chose, its unit and scalor for plotting, and year range. If need to know variable name, user can print all variable names.

But I don't know if you'd like this way or not. 
Fengming

### CODE REVIEW

**Comment by serbinsh** [comment]
Looks good. I think I will do a little more cleanup too. 

I would like to come up with a few example analyses we can provide as illustrations.  e.g. how would you look over ELM output to diagnose a simulation and understand what you are seeing?

I also plan to come up with an initial example showing a data comparison.  I was exploring the portal but need to find a very simple dataset to start with

**Comment by fmyuan** [comment]
I would leave this fork for a while until you pull what you think good enough. 

AND, I just write wiki on how to run the notebook in docker, see the link: https://github.com/fmyuan/fasst_simulation_tools/wiki

For this to work, I temporarily built a docker image and upload to my hub repository - after you put the final into yours, I will have tests with yours.

**Comment by serbinsh** [comment]
I had already created this: https://github.com/FASSt-simulation/fasst_simulation_tools/wiki. We can add to this set of instructions 

Specifically was plannign to have several ddifferent examples starting from this page.  The point was to give folks exampels of different ways to create plots, running python scripts or running Jupyter etc https://github.com/FASSt-simulation/fasst_simulation_tools/wiki/Analyzing-ELM-Output-in-Jupyter-Lab

**Comment by fmyuan** [comment]
So looks like you're OK for me to put those instructions onto your wiki page, I will move all from the forked repo.

**Comment by serbinsh** [comment]
Perhaps - I am wondering if we should first create a single finished example then create the instructions for that one first so we have a template?  or maybe thats what you already have?

**Comment by serbinsh** [comment]
I am also trying to reduce the image size for the jupyter stack now and re-test

**Comment by fmyuan** [comment]
Yes, those instructions are based on what I have finished. More is coming by the other notebook script.

**Comment by fmyuan** [comment]
Already moved and updated wiki page,[ ](https://github.com/FASSt-simulation/fasst_simulation_tools/wiki/Notebook-Example---AK-K64G)

**Pull request merged**
